### ISSUE TITLE
Search under leave application.

### ISSUE THREAD

**Issue by Sameer-Tilak** [joshsoftware/intranet#275]
How the search works. ?

Search term : Kiran
result : I got list of all leaves taken by Kiran Mahale and Kiran Deshmukh. This is expected. 

Search term : Kiran Mahale
result : I got same result as above. Expected is to get leave of Kiran Mahale only. 

Is this bug or the way it is implemented. Will need to change the implementation.

Looks like this is not possible as we store first and last name separately. In that case we should give drop down of employee name to select for list.

**Comment by shintre** [comment]
Selecting name from drop down could be tedious. Instead should we merge the first name and last name into a single field in the backend? 

Later we can remove first name & last name fields

**Comment by pramodshinde** [comment]
I think we split the search term by split space (if its multiword) always first word will be searched in first_name and  remaining later part into last_name. I haven't checked the implementation but this will work in most of the cases.

**Comment by vaibhav8186** [comment]
We have used OR query on first name and last name, so in the above-mentioned case by @Sameer-Tilak sir If we search Kiran Mahale then it will give results for both employees i.e Kiran Mahale and Kiran Deshmukh. 
So, I think we have to change this query, and Instead of search can we have a dropdown of **" approved"** employee's name and **"active"** project names, so that search will be easier for us.
