### ISSUE TITLE
Page crash when user tries to login using Josh account.

### ISSUE THREAD

**Issue by prasadsurase** [joshsoftware/intranet#92]
Sometimes, the login page crashes when user tries to login using Josh account.

**Comment by Shwetakale** [comment]
@prasadsurase Yes few people reported this issue but unable to reproduce it on local. Sometimes we are getting [JWT decode callback token exception](https://github.com/zquestz/omniauth-google-oauth2/issues/218) on exception and this started happening recently. And surprisingly it works for next login request. I will try to reproduce on local otherwise will add fix suggested on above issue.

**Comment by Shwetakale** [comment]
@prasadsurase Fixed and deoployed Let me know if you see this again.
